### ISSUE TITLE
file extenties

### ISSUE THREAD

**Issue by KoopReynders** [jslikker02/Frontend-for-designers-#1]
Al je files hebben geen extensies. 
Je html file moet .htm of .html krijgen. Het css file moet op .css eindigen en javascript file moet op .js eindigen. Je moet dan ook de paden naar je css bestand en js bestand in de html aanpassen

**Comment by jslikker02** [comment]
Voor zover ik kan zien hebben mijn files dit wel? Voor mijn idee het gaat over file.html toch?

**Comment by jslikker02** [comment]
<img width="346" alt="schermafbeelding 2018-07-07 om 20 18 12" src="https://user-images.githubusercontent.com/32230119/42413538-e7c8229e-8222-11e8-8378-aa7605192b5c.png">

**Comment by jslikker02** [comment]
Ik heb het al gevonden. U bedoelde op GitHub. excuus ik begreep het even verkeerd. nu snap ik opeens heel goed waarom het maar niet werkte haha
